/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        int ssum = 0, tsum = 0;
        ssum = calcSum(s);
        tsum = calcSum(t);
        return ((char)(tsum-ssum));
    }
    
    public int calcSum(String str) {
        int sum = 0;
        for(int i = 0; i < str.length();i++) {
            sum += (int)str.charAt(i);
        }
        return sum;
    }
}